### ISSUE TITLE
Set language on a combobox

### ISSUE THREAD

**Issue by david-geiger** [jeka-js/alexandra#10]
Hi Eugene,

Is possible to add a combobox to set an available language for alexandra?

Thanks in advance :)

**Comment by jeka-js** [comment]
Maybe I misunderstood, but this option present in the settings at "Application" tab.

**Comment by david-geiger** [comment]
Oh yes my bad!! Sorry for the noise :)

**Comment by jeka-js** [comment]
That's all right :)
