### ISSUE TITLE
Fetching metadata from online sources

### ISSUE THREAD

**Issue by AcarBurak** [jeka-js/alexandra#12]
Well, since Alexandra is now excellent as it is and since we're spoiled by its elegance and features [:)], I can't help asking the obvious:

Is fetching metadata from online sources in your todo list or is it against your design principles (bloating code or something) or a big hassle to implement?

This would make Alexandra indestructable! Then again if it's not worth your effort, it's excellent as it is and we're grateful for your fine work.

**Comment by jeka-js** [comment]
Hi!
Again you read my mind! :) I know that this function is very much needed and I thought about it.
Now I have an incentive to implement it!

**Comment by AcarBurak** [comment]
This-is-very-very-fine-indeed! Thank you.

**Comment by jeka-js** [comment]
Hi! I've added this function and you can test it. There is only OMDB source (http://www.omdbapi.com/) yet. Later I will try to add other sources.

**Comment by AcarBurak** [comment]
Great news, thank you.

Compilation has failed though:

film.cpp: In static member function ‘static QString Film::ClearTitle(QString)’:
film.cpp:226:23: error: ambiguous overload for ‘operator=’ (operand types are ‘QStringList’ and ‘<brace-enclosed initializer list>’)
         wordsToRemove = { "DHT-Movies", "TheaterRip", "Blue
                       ^
In file included from /usr/include/qt/QtCore/qlist.h:1026:0,
                 from /usr/include/qt/QtCore/qobject.h:43,
                 from /usr/include/qt/QtCore/qiodevice.h:39,
                 from /usr/include/qt/QtCore/qdatastream.h:38,
                 from /usr/include/qt/QtCore/QDataStream:1,
                 from film.h:24,
                 from film.cpp:21:
/usr/include/qt/QtCore/qstringlist.h:107:18: note: candidate: QStringList& QStringList::operator=(const QList<QString>&)
     QStringList &operator=(const QList<QString> &other)
                  ^
/usr/include/qt/QtCore/qstringlist.h:110:18: note: candidate: QStringList& QStringList::operator=(QList<QString>&&)
     QStringList &operator=(QList<QString> &&other) Q_DECL_N
                  ^
/usr/include/qt/QtCore/qstringlist.h:93:7: note: candidate: QStringList& QStringList::operator=(const QStringList&)
 class QStringList : public QList<QString>
       ^
/usr/include/qt/QtCore/qstringlist.h:93:7: note: candidate: QStringList& QStringList::operator=(QStringList&&)
Makefile:1146: recipe for target 'tmp/debug/obj/film.o' failed
make: *** [tmp/debug/obj/film.o] Error 1

**Comment by jeka-js** [comment]
Hmm, looks like this is Qt bug. I've tried to fix. Please, check now.

**Comment by AcarBurak** [comment]
Yes, it works brilliantly. And it works fast. (Oh well, forgot to mention, it's compiled without failure.)

It doesn't fetch tagline or tags, but I guess users shoul and can fill these themselves. As I've already got cover arts, I can't say anything about them, but it should be fine if it could that as well.

**Comment by 0x221E** [comment]
Cover arts are fetched too, just tested.
However, Tagline & Tags are not fetched as @AcarBurak mentioned.

**Comment by AcarBurak** [comment]
Excellent.

**Comment by jeka-js** [comment]
OMDB source does not present all information, like tagline, budget, producer and composer. Later I'll try to add other sources (like IMDb), there will be more information.
Field "tags" is intended for user-defined tags.

**Comment by AcarBurak** [comment]
Very fine.

> Field "tags" is intended for user-defined tags.

Obviously. Sorry about my absent mindednes.

**Comment by AcarBurak** [comment]
Well, neither of those sources seem to find many movies. Perhaps something like a fuzzy find/search capability is needed if possible.

**Comment by jeka-js** [comment]
Can you explain, please?

**Comment by AcarBurak** [comment]
Sorry, for instance, I've got a movie called A RAISIN IN THE SUN, but I've mistakenly entered RAISIN as RAISING, so neither imdb nor others could find it, they could only after I've corrected the spelling. Similar things might have happened with other titles as well, for instance ADAMS RIB instead of ADAM'S RIB.

So, if possible, practical, a search mechanism not querying the exact phrase (title) but an approximation might be useful. Or I'd better learn to enter the correct titles!

**Comment by jeka-js** [comment]
Oh, I understand.
But I use the search requests to these sites and I don't know how (at least for now) I can affect their response. For example, link http://www.imdb.com/search/title?title=A%20RAISING%20IN%20THE%20SUN does not give the right movie.

**Comment by AcarBurak** [comment]
All right, not a big deal really as most of them are because of my own mistakes.
