### ISSUE TITLE
Theme/Style issue

### ISSUE THREAD

**Issue by AcarBurak** [jeka-js/alexandra#13]
Hi again…

A minor issue:

When I choose Default in Style dropdown menu Alexandra doesn't obey my default system-wide qt5 style/theme which I set (in my Fluxbox system) by a very fine utility, qt5ct (a qt5 config tool like the old qt4-config, but a better one).

I've got this line in my ~/.bashrc to use my system-wide qt5 theme configured by qt5ct:

'export QT_QPA_PLATFORMTHEME=qt5ct'

On another note, in Alexandra's Style dropdown menu all those styles are qt4 styles, not qt5 ones and they're not set if I choose one of them. My qt5 styles (fusion, qtcurve, kvantum etc.) aren't listed there.

**Comment by jeka-js** [comment]
Hmm, I did not knew that styles have changed, thanks. :)
On my system I see only GTK+, Fusion and Windows styles, but I have no qt5ct utility. I'll try to fix the style settings soon and you'll be able to check it.

**Comment by AcarBurak** [comment]
My pleasure Eug…!

Well, as you know fusion is the default qt5 style and I've myself installed the others (qtcurve and kvantum), but I use qtcurve and/or fusion really and qtcurve mostly. If you install these other engines you'll see them as well in your Style dropdown menu. You do not need qt5ct for this.

To use the individual engines other than fusion (qtcurve, kvantum, virtuality) one needs to put this in .bashrc:

export QT_STYLE_OVERRIDE=qtcurve

But instead I use qt5ct utility to configure every aspect of the theme, as well as to choose the theme engine itself. To be able to use it I use this in my .bashrc (as mentioned before):

export QT_QPA_PLATFORMTHEME=qt5ct

**Comment by jeka-js** [comment]
Please, try now. I've fixed some things.

**Comment by AcarBurak** [comment]
It works, thank you.

**Comment by jeka-js** [comment]
That's fine :) Thank you for your participation!

**Comment by AcarBurak** [comment]
You're welcome!
