### ISSUE TITLE
Unable To Add Cover Photos From Library.

### ISSUE THREAD

**Issue by 0x221E** [jeka-js/alexandra#15]
I am unable to add cover photos. Clicking on "Open" button doesn't do anything.

System : ArchLinux
Plasma 5
GCC 5.2.0
QT 5.5.0

No warning during compilation, all went smooth.

![Unable to add cover photos](https://cloud.githubusercontent.com/assets/10757422/9978607/55e603d2-5f57-11e5-8a5c-a7bc323d8f81.png)

**Comment by jeka-js** [comment]
It's very strange. Did you tried to test latest version?

**Comment by 0x221E** [comment]
Yup. Tested. Same issue.
![screenshot_20150924_182313](https://cloud.githubusercontent.com/assets/10757422/10073853/8bae52f4-62e9-11e5-9b54-ec03b29d8b74.png)

**Comment by jeka-js** [comment]
I've tried to fix this issue. Please, check it.

**Comment by 0x221E** [comment]
It's fixed now.
![screenshot_20150926_134526](https://cloud.githubusercontent.com/assets/10757422/10116558/f1982e48-6454-11e5-9d83-f01bc5831fbd.png)

Thanks for the support. Such a nice app. Keep up the good work :+1:

**Comment by jeka-js** [comment]
Thank you! :)
