### ISSUE TITLE
Audio as well?

### ISSUE THREAD

**Issue by AcarBurak** [jeka-js/alexandra#18]
Hi Eugene,

If it's not unpractical or against your principles, adding audio as well would be very fine.

There's a very brilliant (qt5) audio player, [Cantata](https://github.com/CDrummond/cantata) (an mpd client), with very fine library and playlist management and very elegant and logical interface like Alexandra (screenshot below). Yet being an mpd client, it suffers from mpd's glitches now and then, that is, all of a sudden, after some obscure package update mpd stops working. Apart from Cantata, the only real alternative is another qt5 player, Yarock having mpv as its audio engine, but it's not as elegant as Cantata. Besides, there's no complete audio-video player/manager let alone a brilliant one combining Alexandra and Cantata.

![cantata](https://cloud.githubusercontent.com/assets/1426842/13036883/f32a0916-d37b-11e5-8a0b-87ad444767ae.png)

**Comment by jeka-js** [comment]
Hi Acar,

Unfortunately, I was planning Alexandra only as a video library and I'll not add support for audio.
Once I thought about creating a separate program for this purpose, but then changed my mind.

Sorry :)

**Comment by AcarBurak** [comment]
No problem at all! Thanks a lot for the already indispensable utility.
