### ISSUE TITLE
No posters

### ISSUE THREAD

**Issue by AcarBurak** [jeka-js/alexandra#19]
With the latest version and new database no posters any more; won't load posters.

**Comment by jeka-js** [comment]
Hi Acar,

I hope you saved backup :laughing: 

I have a suggestion that your image files have the extension (probably .png). They were in earlier versions of the program and I had not thought about it.

If so, try to remove extension from few files and check the program.

**Comment by AcarBurak** [comment]
Hi...

I've been backing up everything (snapshots), so no worry about there.

Yes, removing the .png extension solves the issue. Thank you.

**Comment by jeka-js** [comment]
Hi,

Can you please test the latest version with your old database (if you have not deleted it)?

**Comment by AcarBurak** [comment]
Hi Eugene,

Yes, the covers appear all right, but do not link to the actual movie files any more. Then I use film scanner and this time I get double files in alexandra window, one for the covers and one for the actual movie files without covers.

**Comment by jeka-js** [comment]
I found an issue in "Moved films" function. That's what you meant?

**Comment by AcarBurak** [comment]
Yes, seemingly.
