### ISSUE TITLE
Grid view of embedded DVD covers

### ISSUE THREAD

**Issue by AcarBurak** [jeka-js/alexandra#2]
You may already have thought about it, but a grid view of embedded DVD covers (like iTunes or Vlc) would be very very fine as it's a great convenience to have visual clue while browsing a media library.

Please see the attached file which shows my library in Vlc. I've ripped my DVDs to mkv and embedded DVD covers. Vlc is fine, but this feature of it is an after thought and a bit shaky. Besides such an implementation in your otherwise fine software would make it possible to use any other player (mpv etc.) as well as making Alexandra unique.

![vlc-grid](https://cloud.githubusercontent.com/assets/1426842/6316267/e5ef151e-ba29-11e4-9b3f-50f8cb412aa9.png)

**Comment by jeka-js** [comment]
Hi! First of all, thank you for your feedback. :)
This feature is in my plans. But I can not say exactly when it will be implemented.

**Comment by AcarBurak** [comment]
Very fine. Thank you sir!

**Comment by AcarBurak** [comment]
Heyyyy!!! Thank you sir!. This precious software must be known widely.

**Comment by AcarBurak** [comment]
The Alexandra version of my collection without the VLC glitches/issues and with more feauters:
![alexandra](https://cloud.githubusercontent.com/assets/1426842/9454284/6c5cf960-4ac9-11e5-8e67-2e4afcc0f8e0.png)

**Comment by AcarBurak** [comment]
Alexandra has been advertised here:

https://bbs.archlinux.org/viewtopic.php?pid=1556255#p1556255

**Comment by jeka-js** [comment]
I am glad that someone likes my program! :)
Link doesn't work.

**Comment by AcarBurak** [comment]
No idea, works here. Can you try this:

https://bbs.archlinux.org/viewtopic.php?pid=1556255

**Comment by jeka-js** [comment]
It was necessary to be registered. :) Now I see.
I guess this issue can be closed?

**Comment by AcarBurak** [comment]
Sorry to bother you. Yes, sure, it's done. Thanks again.
