### ISSUE TITLE
Improved alexandra

### ISSUE THREAD

**Issue by david-geiger** [jeka-js/alexandra#3]
Hello alexandra Team,

I'm Geiger David and I'm part of the Mageia packager Team. I think that the alexandra software is very attractive and I'd like to import this one on Mageia repositories and maintain it.
I've built and successfully tested it on a local machine.

By cons before imported it on Mageia, I propose you to improve a bit the alexandra package part:

1. Can you create a desktop file for linux package (rpm/deb)?
2. Can you provide an alexandra icon of png and/or svg format? (min. 256x256px)
3. Can you create a French translation file that I can translate it?
4. Can you create a Make_install part that all files are automatically installed during build?
5. Can you create a tarball with current version (.tar.gz and .zip) into Release section from your github project?

For make_install should be:
- /usr/bin/alexandra
- /usr/share/applications/alexandra.desktop
- /usr/share/icons/alexandra.png or /usr/share/icons/hicolor/NxN/apps/alexandra.png (N=px)
- /usr/share/icons/hicolor/scalable/apps/alexandra.svg

Thanks in advance for your great job!

Best regards David.

**Comment by jeka-js** [comment]
Hi David!
I have completed the first four points. Please check. You can translate the file "lang/alexandra_fr.ts" and then I can create a Release.

**Comment by david-geiger** [comment]
Hi Eugene,

Done for French translation!

Please add the 2 translators to the list in about dialog.

Thanks :)

**Comment by david-geiger** [comment]
Also is alexandra compatible with Qt 5.5 ?
I mean the build :)

Because on new Qt 5.5 there is some new change.

**Comment by jeka-js** [comment]
I added translators and created Release.
With Qt 5.5 have not tested, but should work.

**Comment by david-geiger** [comment]
Warning with desktop file (seems there are duplicate keys):

alexandra.x86_64: W: invalid-desktopfile /usr/share/applications/alexandra.desktop file contains multiple keys named "GenericName[ru]" in group "Desktop Entry"

alexandra.x86_64: W: invalid-desktopfile /usr/share/applications/alexandra.desktop file contains multiple keys named "Comment[ru]" in group "Desktop Entry"

**Comment by jeka-js** [comment]
Oh, hurried, sorry. Fixed.

**Comment by david-geiger** [comment]
Thanks Eugene!

Also I confirm that compilation works with Qt 5.5.

I think this issue can be closed. :)

Best regards David.

**Comment by jeka-js** [comment]
I am very glad, thank you! :)
