### ISSUE TITLE
Screenwriter and Composer tags

### ISSUE THREAD

**Issue by AcarBurak** [jeka-js/alexandra#6]
would be appreciated as the former is the most crucial component of a (good) movie as some great directors/writers (Hitchcock, Billy Wilder, Mel Brooks…) have mentioned.

And with some movies the composer is as much crucial as the director: Morricone, Rota, Badalamenti, Herrmann…

**Comment by jeka-js** [comment]
Done :)

**Comment by AcarBurak** [comment]
Thank you, sir!
