### ISSUE TITLE
Advance search in simple search as well

### ISSUE THREAD

**Issue by AcarBurak** [jeka-js/alexandra#7]
would be a fine convenience, that is, to be able to filter by any keyword/tag available in advance search.

**Comment by jeka-js** [comment]
Done, but not fully tested. So it is at your own risk. :stuck_out_tongue_closed_eyes:

**Comment by AcarBurak** [comment]
Brilliant. Works.

But this simple search needs a keyboard shortcut, in fact, Control+F is better suited for this than the advance search. Advance search has its icon on the toolbar and with this new feature I don't think the advance search will be used much if any!

Really, a secondary shortcut to clear the previous search would be still finer, for example, Escape.

**Comment by jeka-js** [comment]
Yes, I was going to make this setting.

**Comment by AcarBurak** [comment]
You are good and wise!

**Comment by jeka-js** [comment]
Settings shortcuts added.
I found it convenient to use the "Backspace" key to enter the quick search.
To send a focus to the films list use the "Esc" key. Another press of "Esc" clears the search line. :)

**Comment by AcarBurak** [comment]
Much better! Thank you.
